# This file was generated by GoReleaser. DO NOT EDIT.
cask "tgctl-cli" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "12329b525727f7d0b7ca4fbcc5db9827b0c74adc618c0b3c0d0958ff490105d1"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3c5f7b81f2641ba6b5e3d866dc03f787a864ac31cd716d0af3d37f5b4e4c85f"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abd6a50646b6ca4802dda59fec3221bf5c50da4a800256e60ef689ab12bfa2fe"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c384a09e05421a8d5c79f8897cf54ffad04dbeebcf6ff1e4beb6ed64d390666"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tgctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/tgctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tgctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tgctl"]
  end

  # No zap stanza required

end
