# This file was generated by GoReleaser. DO NOT EDIT.
cask "tgctl-cli" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "a7b4f88b0e06d96a9c8ce7aab4e195c4970a98ba16110070fcbe3f69c2c76e9b"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6220e41524fb07cd94d05b715fa7226fab65cf4abaa20799fae2d90e0ebe4f7b"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7a8f66e256115d2488d5318c18e0c055fef176177156aac4a82e9333b10870d"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9ca9ee1811948210a41ee7a2f5aa34892a08d8007b09b9601430d0652b6fe3a"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tgctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/tgctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tgctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tgctl"]
  end

  # No zap stanza required

end
