# This file was generated by GoReleaser. DO NOT EDIT.
cask "tgctl-cli" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "30596167b66006529f2c5755db3c85fd38db30774254bc2c1fb5b665b523959a"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "204f3e856805341426127e5dea740ce367c3dfc52c4ffd7a042e7b0d85622137"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e3c282cd8f0712fa68502fb859bd76f47a658dc85a800dfabef01b406eed0a2"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1426bb8cc2ae28893bdb1f97ffa18d0e62696ef5f9aa1233f43e67fb17bf2d3b"
      url "https://github.com/jjuanrivvera/tgctl/releases/download/v#{version}/tgctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tgctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/tgctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tgctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tgctl"]
  end

  # No zap stanza required

end
